server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true
      directory: /home/lhf/logs
      prefix: access_log

# spring security

#是否开启定时任务
quartz:
  open: false

spring:
  application:
    name: demo

  data:
    redis:
      host: localhost
      password:
      port: 6379


  session:
    timeout: 3000
    redis:
      namespace: spring:session
      flush-mode: on_save

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lihaifeng
    url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai

  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
    fallback-to-system-locale: true

  # 调度框架
  quartz:
    auto-startup: ${quartz.open}
    startup-delay: 1
    job-store-type: jdbc
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DemoScheduler
          threadPool:
            threadCount: 5
    jdbc:
      initialize-schema: never

  security:
    user:
      name: user
      password: user


  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    cache-enabled: true

rest:
  server:
    uri: http://localhost:8080

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.csits.demo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

